
name: .NET Tests and Docker Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8'

    # Install dependencies
    - name: Install dependencies
      run: dotnet restore

    # Build project
    - name: Build
      run: dotnet build --no-restore

    # Run tests
    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    # Publish test results
    - name: Publish test results
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/TestResults/*.xml'

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx (for multi-platform builds, optional)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/blog_dotnet:latest .

    # Push Docker image to Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/blog_dotnet:latest .
